version: '2'
services:
  mojo:
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - OAUTH_GITHUB_KEY=${OAUTH_GITHUB_KEY}
      - OAUTH_GITHUB_SECRET=${OAUTH_GITHUB_SECRET}
      - OAUTH_FACEBOOK_KEY=${OAUTH_FACEBOOK_KEY}
      - OAUTH_FACEBOOK_SECRET=${OAUTH_FACEBOOK_SECRET}
      - OAUTH_GOOGLE_KEY=${OAUTH_GOOGLE_KEY}
      - OAUTH_GOOGLE_SECRET=${OAUTH_GOOGLE_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    image: project-x:latest
    ports:
     - "8080:8080"
    depends_on:
     - postgresql
    volumes:
      - ./lib:/opt/project-x/lib
      - ./public:/opt/project-x/public
      - ./templates:/opt/project-x/templates
      - ./t:/opt/project-x/t
  postgresql:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql
